[package]
name = "the_carrion_language"
version = "0.1.0"
edition = "2024"

[dependencies]
indoc = "2.0.6"
once_cell = "1.19"
rustyline = "14.0"

[[bin]]
name = "carrion"
path = "src/main.rs"


[lib]
name = "the_carrion_language"
path = "src/lib.rs"
